image: ghcr.io/cirruslabs/android-sdk:34

variables:
  ANDROID_SDK_ROOT: "/sdk"
  ANDROID_HOME: "/sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper/
    - .gradle/caches/
    - /sdk/platforms/
    - /sdk/build-tools/

stages:
  - setup
  - test
  - build

before_script:
  - echo "Checking environment..."
  - echo "$ANDROID_SDK_ROOT"
  - echo "$ANDROID_HOME"
  - ls -la /sdk || echo "SDK directory is missing!"
  - export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
  - echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
  - chmod +x gradlew

setup:
  stage: setup
  script:
    - yes | sdkmanager --licenses
    - sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"

test:
  stage: test
  script:
    - ./gradlew test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
